metadata:
    org:
        id: "75"
        handle: charukakarunanayake
    displayName: tc4
    displayType: ballerinaService
    description: one before tc5
    version: 1.0.0
    projectId: 400203d5-98b7-49a7-bc9d-c5acf3d8282e
    accessibility: external
    repository:
        appSubPath: tc4
        orgApp: CharukaK
        nameApp: monorepo-test-cli
        branchApp: main
        gitProvider: github
id: b76c01e1-6c21-42eb-a838-1f8ad8e19a56
handler: shnrdr
commitHash: ""
