id: 5f66e9d6-dd87-4e37-8605-b02d70ef579b
orgId: 3053
name: monorepo-test-cli
version: 1.0.0
createdDate: ""
handler: ""
region: US
description: ""
repository: monorepo-test-cli
branch: main
gitProvider: github
gitOrganization: CharukaK
