id: 6efa62a1-2528-4336-bcdd-49ca1ba23e0e
orgId: 3053
name: monorepo-test-cli
version: 1.0.0
createdDate: ""
handler: ""
region: US
description: Hehe
repository: monorepo-test-cli
branch: main
gitProvider: github
gitOrganization: CharukaK
