id: 61704c36-4961-420e-8d73-f36d1e8c5758
orgId: 75
name: monorepo-test-cli
version: 1.0.0
createdDate: ""
handler: ""
region: US
description: Hehe
repository: monorepo-test-cli
branch: main
gitProvider: github
gitOrganization: CharukaK
