id: ""
orgId: 3053
name: monorepo-test-cli
version: 1.0.0
createdDate: ""
handler: ""
region: US
description: mono repo test
repository: monorepo-test-cli
branch: main
gitProvider: github
gitOrganization: CharukaK
