id: 400203d5-98b7-49a7-bc9d-c5acf3d8282e
orgId: 75
name: monorepo-test-cli
version: 1.0.0
createdDate: ""
handler: ""
region: US
description: Mono repo stuff
repository: monorepo-test-cli
branch: main
gitProvider: github
gitOrganization: CharukaK
